dist: jammy

# safelist
branches:
  only:
  - master

language: python
python:
- "3.10"
install:
#- pip install -r requirements.txt
- pip install Flask pymongo requests
- pip install git+https://github.com/dag-hammarskjold-library/dlx

stages:
  - name: Dev
    if: branch = master

jobs:
  include:
    - stage: Dev
      script:
      - zappa update -s zappa_settings.json dev